Proper set of pkg scripts

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,22 +1,61 @@
-#! /bin/sh
+#!/bin/sh
+# postinst script for nrflows
+#
+# see: dh_installdeb(1)
 
-echo "postinstall XC"
+set -e
 
-XC_HOME=/var/lib/ai-and-it/xc
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see https://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-python3 -m pip install Django==3.1.1
 
-$XC_HOME/ci/config-system.sh
+case "$1" in
+    configure)
 
-dpkgout=$(dpkg -l xc-usense)
-dpkgres=$?
+	echo "postinstall XC"
 
-echo "dpkg -l xc-usense"
-echo $dpkgout
+	XC_HOME=/var/lib/ai-and-it/xc
 
-xcUStatus=$(echo -n "$dpkgout" | tail -n1 | cut -f 1 -d ' ')
+	python3 -m pip install Django==3.1.1
 
-if test $dpkgres = 0 && test $xcUStatus = ii; then
-    echo "XC app xc-usense is installed, reconfigure"
-    dpkg-reconfigure xc-usense
-fi
+	$XC_HOME/ci/config-system.sh
+
+	dpkgout=$(dpkg -l xc-usense)
+	dpkgres=$?
+
+	echo "dpkg -l xc-usense"
+	echo $dpkgout
+
+	xcUStatus=$(echo -n "$dpkgout" | tail -n1 | cut -f 1 -d ' ')
+
+	if test $dpkgres = 0 && test $xcUStatus = ii; then
+	    echo "XC app xc-usense is installed, reconfigure"
+	    dpkg-reconfigure xc-usense
+	fi
+
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
